name: golangci-lint
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    container: ghcr.io/cshum/imagor-base:vips8.18.6-r14-dev
    env:
      CGO_ENABLED: "1"
      PKG_CONFIG_PATH: /opt/imagor/lib/pkgconfig
      CGO_CFLAGS: -I/opt/imagor/include
      CGO_LDFLAGS: -L/opt/imagor/lib -Wl,-rpath,/opt/imagor/lib
      LD_LIBRARY_PATH: /opt/imagor/lib
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.14.0
